name: CI

on: [push, pull_request] # on all pushes and PRs

jobs:
  ros1_bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ros-tooling/setup-ros@v0.6
      - name: Build and test ros1-bridge
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: ros1_bridge
          target-ros1-distro: noetic
          target-ros2-distro: humble
